# Generated by Django 2.0.6 on 2018-06-13 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortly',
            fields=[
                ('url_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=250, unique=True)),
                ('visited', models.IntegerField(default=0)),
            ],
        ),
    ]
